# connector.name=mongodb

# mongodb.connection-url=mongodb+srv://therealmanraj:therealmanraj@cluster0.co763wd.mongodb.net/?appName=Cluster0
# mongodb.schema-collection=_schema

# # mongodb.connection-url=mongodb+srv://admin:8nAp7UJiLys1NcaN@cluster0.ix4lzb2.mongodb.net
# # mongodb.schema-collection=_schema

# mongodb.projection-pushdown-enabled=false