# ── Catalog 1: app_db (test/dummy cluster) ────────────────────────────────────
# File: /etc/trino/catalog/mongo_app.properties
# Access in Superset as: mongo_app.app_db.users

connector.name=mongodb
mongodb.connection-url=mongodb+srv://therealmanraj:therealmanraj@cluster0.co763wd.mongodb.net/?appName=Cluster0
mongodb.schema-collection=_schema
mongodb.projection-pushdown-enabled=true
