services:
  postgres:
    extends:
      file: ./services/postgres/docker-compose.yaml
      service: postgres

  adminer:
    extends:
      file: ./services/postgres/docker-compose.yaml
      service: adminer

  superset-db:
    extends:
      file: ./services/superset/docker-compose.yaml
      service: superset-db

  superset-init:
    extends:
      file: ./services/superset/docker-compose.yaml
      service: superset-init

  superset:
    extends:
      file: ./services/superset/docker-compose.yaml
      service: superset

  trino:
    extends:
      file: ./services/trino/docker-compose.yaml
      service: trino

volumes:
  superset-db-data:
    external: false
  superset_home:
    external: false
  postgres-db-volume:
    external: false
