services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
      TZ: America/Vancouver
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./SQL-Scripts:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test:
        ["CMD-SHELL", 'pg_isready -U "$${POSTGRES_USER}" -d "$${POSTGRES_DB}"']
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "0.0.0.0:8081:8080"
    expose:
      - "8081"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres-db-volume:
    external: false
