services:
  trino:
    image: trinodb/trino:479
    container_name: trino
    restart: unless-stopped
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx3g -Xms1g"
    volumes:
      - ./catalog:/etc/trino/catalog:ro
